import { jsxFactory, IvirtualNode } from "@cimo/jsmvcfw/dist/src/Main";

const viewMvcController = (): IvirtualNode => {
    return (
        <div class="view_content">
            <h1>Controller</h1>
            <table>
                <colgroup>
                    <col class="cell" />
                    <col class="cell" />
                    <col class="cell" />
                </colgroup>
                <thead>
                    <tr class="row not_hover">
                        <th class="cell">Signature</th>
                        <th class="cell">Return type</th>
                        <th class="cell">Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="row">
                        <td class="cell">{"variableObject"}</td>
                        <td class="cell">{"modelIndex.Ivariable"}</td>
                        <td class="cell">Holds the reactive variables bound to the view.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"methodObject"}</td>
                        <td class="cell">{"modelIndex.Imethod"}</td>
                        <td class="cell">Holds the reactive method bound to the view.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"constructor()"}</td>
                        <td class="cell">{"void"}</td>
                        <td class="cell">Initializes variables.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"elementHookObject"}</td>
                        <td class="cell">{"modelIndex.IelementHook"}</td>
                        <td class="cell">
                            Keeps references to DOM element hooks for dynamic updates (with this tag in the view {"jsmvcfw-elementHookName='xxx'"})
                        </td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"variable()"}</td>
                        <td class="cell">{"void"}</td>
                        <td class="cell">Binds reactive variables and assigns controller methods for the view.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"variableEffect(watch: IvariableEffect)"}</td>
                        <td class="cell">{"void"}</td>
                        <td class="cell">Sets up watchers for variable changes.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"view()"}</td>
                        <td class="cell">{"IvirtualNode"}</td>
                        <td class="cell">Returns the virtual DOM node generated by the view function.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"event()"}</td>
                        <td class="cell">{"void"}</td>
                        <td class="cell">Event registration logic.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"subControllerList()"}</td>
                        <td class="cell">{"Icontroller[]"}</td>
                        <td class="cell">Populate the sub-controllers list (use this tag in the view {"jsmvcfw-controllerName='xxx'"}).</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"rendered()"}</td>
                        <td class="cell">{"void"}</td>
                        <td class="cell">Called after the view is rendered.</td>
                    </tr>
                    <tr class="row">
                        <td class="cell">{"destroy()"}</td>
                        <td class="cell">{"void"}</td>
                        <td class="cell">Cleans up resources when the controller is destroyed.</td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
};

export default viewMvcController;
